input:
  project_name: "otter-12S"
  fastqs_path: "otter-12s/data-fqs"
  reference_dir: "mammalian-12s-ref-seq"
  metadata: "otter-12s/metadata-otter.tsv"

output:
  processed_data: "otter-12s/processed"

params:
  report_name:
    multiqc_report_name: "otter-12"
  preprocessing:
    pair_end: 1 # 0 is false
    trim_primer: 1 # 1 is true
    primer_length: 0
    num_samples: 6
    reads_threshold: 100 # minimum feature count of the taxon that can be assigned on the report
    truncation_length: 100 # if read length longer than this, it will be truncated
  classification:
    pident: 0.8 # percent identification on pairwise alignment
    min_consensus: 0.51
  relative_abundance:
    level: all
  krona_chart:
    group_by: sample-id
    level: all


